### ISSUE TITLE
Snowball version

### ISSUE THREAD

**Issue by AmenRa** [snowballstem/pystemmer#37]
Hi, does this library point to the latest Snowball version?

From my understanding, the latest Snowball version is 2.2.0, but this library's setup.py points to version 2.1.0 (DEFAULT_URI).
Is this intended?

**Comment by ojwb** [comment]
Thanks for pointing this out - I've pushed a fix.

I've also updated the PyStemmer version to align with the libstemmer_c version - it looks like we failed to update that when we updated to libstemmer_c 2.1.0.  I've adjusted the code so having them different now requires deliberate choice (I could see we might need to version a PyStemmer-specific update).

@felixonmars Please can you upload PyStemmer 2.2.0 to pypi?

**Comment by ojwb** [comment]
@felixonmars I've created and pushed a v2.2.0 tag (it seems we haven't tagged releases previously!)

**Comment by felixonmars** [comment]
I have pushed the source tarball. Thanks!

**Comment by felixonmars** [comment]
It seems building from the source tarball is broken because it doesn't contain necessary files for the vendored libstemmer_c library. 

This should be an inconsistency between the renamed libstemmer_c-$VER directory and the unversioned entry in MANIFEST.in.

**Comment by ojwb** [comment]
@felixonmars Wondering how best to fix this - I'm wondering if we should stop trying to bundle libstemmer_c at all since we support downloading it automatically?  It's also dead weight if you want to use a system install of libstemmer.

**Comment by sthen** [comment]
Hi, downloading at build time is a bit of a problem for some distro packagers (on various OS, build machines intentionally don't have network access). There are ways to handle it but it's generally simpler for us if either the files are included, or it can use a system install (which works, but afaict currently requires patching setup.py).

**Comment by ojwb** [comment]
Indeed - I'd expect a distro package of pystemmer would want to build against a distro package of libstemmer_c anyway.

But if you want to make a package including libstemmer_c sources, that's still easy to do as the downloading is done lazily so you can just include the expected version of the libstemmer_c tarball in your source package.  The downloading code will see it's already there and just use it.  We can mention that trick in the docs (which will need an update for this anyway).

**Comment by sthen** [comment]
I think it's mostly Linux distributions (maybe mostly Debian-based?) which use separate locally-generated "source pacakges" - the ports systems on BSDs generally fetch directly from upstream sources. It can still be done (via fetching multiple distfiles and unpacking into place), it's just a pain to do (:

Anyway using system libstemmer with #39 is altogether better anyway, thanks.

**Comment by ojwb** [comment]
(RPM-based distros have source packages too.)

I've now pushed a commit to drop the bundling of libstemmer_c.

@felixonmars Can you make a PyPI upload?  If you set `version_str = '2.2.0.1'` in `setup.py` that should do the right thing.

**Comment by felixonmars** [comment]
With https://github.com/snowballstem/pystemmer/commit/a2ef419ec9737b44776e8f75323d5adef9cf79a9 I managed to generate a usable source distribution by setting `PYSTEMMER_SYSTEM_LIBSTEMMER`. Not sure if there is a better way but at least it's usable now :)

**Comment by ojwb** [comment]
Thanks.  I've pushed a tagged commit with the new version number.

I've little idea what the expectations of a typical pypi user would be here, but we could make using the system libstemmer the default, with an explicit way to specify to use a private build.

Otherwise I suppose the handling of `PYSTEMMER_SYSTEM_LIBSTEMMER` needs to be later and on a code path that doesn't get taken when making a source distribution, or making a source distribution needs to implicitly set it.

Or we just live with having to set it by hand.

**Comment by felixonmars** [comment]
We need a way to detect the system libstemmer then, like using pkg-config etc, if we're going to default to system libstemmer.

A special treatment for generating source distributions would work too, of course :)

**Comment by ojwb** [comment]
Hmm indeed - if system libstemmer is the default it really needs to "just work", at least for reasonable configurations.  Otherwise we'll have frustrated users and a lot more bug reports to respond to.

I had a look, but I don't really know anything about setuptools and couldn't see how to change things to avoid needing to set `PYSTEMMER_SYSTEM_LIBSTEMMER` when creating a source distribution, but happy to take a patch from someone who does.

The issue reported here has been addressed, so closing.
